// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	clients "github.com/mwhite7112/woodpantry-matching/internal/clients"
	mock "github.com/stretchr/testify/mock"
)

// MockDictionaryFetcher is an autogenerated mock type for the DictionaryFetcher type
type MockDictionaryFetcher struct {
	mock.Mock
}

type MockDictionaryFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDictionaryFetcher) EXPECT() *MockDictionaryFetcher_Expecter {
	return &MockDictionaryFetcher_Expecter{mock: &_m.Mock}
}

// GetIngredient provides a mock function with given fields: ctx, id
func (_m *MockDictionaryFetcher) GetIngredient(ctx context.Context, id string) (*clients.IngredientDetail, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetIngredient")
	}

	var r0 *clients.IngredientDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*clients.IngredientDetail, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *clients.IngredientDetail); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clients.IngredientDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDictionaryFetcher_GetIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIngredient'
type MockDictionaryFetcher_GetIngredient_Call struct {
	*mock.Call
}

// GetIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDictionaryFetcher_Expecter) GetIngredient(ctx interface{}, id interface{}) *MockDictionaryFetcher_GetIngredient_Call {
	return &MockDictionaryFetcher_GetIngredient_Call{Call: _e.mock.On("GetIngredient", ctx, id)}
}

func (_c *MockDictionaryFetcher_GetIngredient_Call) Run(run func(ctx context.Context, id string)) *MockDictionaryFetcher_GetIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDictionaryFetcher_GetIngredient_Call) Return(_a0 *clients.IngredientDetail, _a1 error) *MockDictionaryFetcher_GetIngredient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDictionaryFetcher_GetIngredient_Call) RunAndReturn(run func(context.Context, string) (*clients.IngredientDetail, error)) *MockDictionaryFetcher_GetIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubstitutes provides a mock function with given fields: ctx, ingredientID
func (_m *MockDictionaryFetcher) GetSubstitutes(ctx context.Context, ingredientID string) ([]clients.IngredientSubstitute, error) {
	ret := _m.Called(ctx, ingredientID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubstitutes")
	}

	var r0 []clients.IngredientSubstitute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]clients.IngredientSubstitute, error)); ok {
		return rf(ctx, ingredientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []clients.IngredientSubstitute); ok {
		r0 = rf(ctx, ingredientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]clients.IngredientSubstitute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ingredientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDictionaryFetcher_GetSubstitutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubstitutes'
type MockDictionaryFetcher_GetSubstitutes_Call struct {
	*mock.Call
}

// GetSubstitutes is a helper method to define mock.On call
//   - ctx context.Context
//   - ingredientID string
func (_e *MockDictionaryFetcher_Expecter) GetSubstitutes(ctx interface{}, ingredientID interface{}) *MockDictionaryFetcher_GetSubstitutes_Call {
	return &MockDictionaryFetcher_GetSubstitutes_Call{Call: _e.mock.On("GetSubstitutes", ctx, ingredientID)}
}

func (_c *MockDictionaryFetcher_GetSubstitutes_Call) Run(run func(ctx context.Context, ingredientID string)) *MockDictionaryFetcher_GetSubstitutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDictionaryFetcher_GetSubstitutes_Call) Return(_a0 []clients.IngredientSubstitute, _a1 error) *MockDictionaryFetcher_GetSubstitutes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDictionaryFetcher_GetSubstitutes_Call) RunAndReturn(run func(context.Context, string) ([]clients.IngredientSubstitute, error)) *MockDictionaryFetcher_GetSubstitutes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDictionaryFetcher creates a new instance of MockDictionaryFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDictionaryFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDictionaryFetcher {
	mock := &MockDictionaryFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
