// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	clients "github.com/mwhite7112/woodpantry-matching/internal/clients"
	mock "github.com/stretchr/testify/mock"
)

// MockRecipeFetcher is an autogenerated mock type for the RecipeFetcher type
type MockRecipeFetcher struct {
	mock.Mock
}

type MockRecipeFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecipeFetcher) EXPECT() *MockRecipeFetcher_Expecter {
	return &MockRecipeFetcher_Expecter{mock: &_m.Mock}
}

// GetRecipes provides a mock function with given fields: ctx
func (_m *MockRecipeFetcher) GetRecipes(ctx context.Context) ([]clients.Recipe, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipes")
	}

	var r0 []clients.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]clients.Recipe, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []clients.Recipe); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]clients.Recipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRecipeFetcher_GetRecipes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecipes'
type MockRecipeFetcher_GetRecipes_Call struct {
	*mock.Call
}

// GetRecipes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRecipeFetcher_Expecter) GetRecipes(ctx interface{}) *MockRecipeFetcher_GetRecipes_Call {
	return &MockRecipeFetcher_GetRecipes_Call{Call: _e.mock.On("GetRecipes", ctx)}
}

func (_c *MockRecipeFetcher_GetRecipes_Call) Run(run func(ctx context.Context)) *MockRecipeFetcher_GetRecipes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRecipeFetcher_GetRecipes_Call) Return(_a0 []clients.Recipe, _a1 error) *MockRecipeFetcher_GetRecipes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRecipeFetcher_GetRecipes_Call) RunAndReturn(run func(context.Context) ([]clients.Recipe, error)) *MockRecipeFetcher_GetRecipes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRecipeFetcher creates a new instance of MockRecipeFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecipeFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecipeFetcher {
	mock := &MockRecipeFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
