// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	clients "github.com/mwhite7112/woodpantry-matching/internal/clients"
	mock "github.com/stretchr/testify/mock"
)

// MockPantryFetcher is an autogenerated mock type for the PantryFetcher type
type MockPantryFetcher struct {
	mock.Mock
}

type MockPantryFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPantryFetcher) EXPECT() *MockPantryFetcher_Expecter {
	return &MockPantryFetcher_Expecter{mock: &_m.Mock}
}

// GetPantry provides a mock function with given fields: ctx
func (_m *MockPantryFetcher) GetPantry(ctx context.Context) ([]clients.PantryItem, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPantry")
	}

	var r0 []clients.PantryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]clients.PantryItem, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []clients.PantryItem); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]clients.PantryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPantryFetcher_GetPantry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPantry'
type MockPantryFetcher_GetPantry_Call struct {
	*mock.Call
}

// GetPantry is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPantryFetcher_Expecter) GetPantry(ctx interface{}) *MockPantryFetcher_GetPantry_Call {
	return &MockPantryFetcher_GetPantry_Call{Call: _e.mock.On("GetPantry", ctx)}
}

func (_c *MockPantryFetcher_GetPantry_Call) Run(run func(ctx context.Context)) *MockPantryFetcher_GetPantry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPantryFetcher_GetPantry_Call) Return(_a0 []clients.PantryItem, _a1 error) *MockPantryFetcher_GetPantry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPantryFetcher_GetPantry_Call) RunAndReturn(run func(context.Context) ([]clients.PantryItem, error)) *MockPantryFetcher_GetPantry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPantryFetcher creates a new instance of MockPantryFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPantryFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPantryFetcher {
	mock := &MockPantryFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
